# This is a TOML document. Boom.

title = "Gin web framework starter kit"

# Gin mode : debug release test
gin_mode = "debug"

[database]
host = "192.168.0.11"
port = "3306"
user = "user"
password = "password"
db = "db_name"

[redis]
host = "192.168.0.22"
port = "6397"
auth = "auth text"
